server:
  port: 80
  servlet:
    context-path: /flowable

flowable:
  #关闭定时任务JOB
  async-executor-activate: false
  #  将databaseSchemaUpdate设置为true。当Flowable发现库与数据库表结构不一致时，会自动将数据库表结构升级至新版本。
  #database-schema-update: false
spring:
  # activiti
#  flowable:
#    #每次应用启动不检查Activiti数据表是否存在及版本号是否匹配，提升应用启动速度
#    database-schema-saveOrUpdate: true
#    check-process-definitions: true
#    process-definition-location-prefix: classpath:/processes/
#    process-definition-location-suffixes:
#      -**.bpmn
#      -**.bpmn20.xml
#    #保存历史数据级别设置为full最高级别，便于历史数据的追溯
#    history-level: full
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://146.56.192.87:3306/flowable_demo?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&nullCatalogMeansCurrent=true
    jdbc-url: jdbc:mysql://146.56.192.87:3306/flowable_demo?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&nullCatalogMeansCurrent=true
    username: oyc
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.oycbest.oyc.domain
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志
    cache-enabled: false
  global-config:
    db-config:
      #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      id-type: auto
      #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
      field-strategy: not_empty
      #驼峰下划线转换
      column-underline: true
      #逻辑删除配置
      logic-delete-value: 0
      logic-not-delete-value: 1
      db-type: mysql
      #刷新mapper 调试神器
      refresh: false






